apiVersion: v1
kind: Pod
metadata:
  name: simple-echo
  labels:
    app: my-nginx
spec:
  containers:
    - name: mynginx
      image: nginx:latest
      env:
      - name: BACKEND_HOST
        value: localhost:8080
      ports:
      - containerPort: 80
    - name: myecho
      image: gihyodocker/echo:latest
      ports:
      - containerPort: 8080